### ISSUE TITLE
Privacy Police

### ISSUE THREAD

**Issue by Luciana478** [Luciana478/Dizar-Mobile#1]
Hey, what about we add a new **privacy police**?

This would be helpfull!

**Comment by RafaelCanarei5** [comment]
Great, @Luciana478! How about we made this in **Markdown** instead **create a Word document**?

**Comment by RafaelCanarei5** [comment]
But... needs to be acceptable!!!

**Comment by Luciana478** [comment]
Great idea, @RafaelCanarei5!

**Comment by Luciana478** [comment]
Thank you to create, @RafaelCanarei5!

**Comment by RafaelCanarei5** [comment]
But... And our website? I can create it on https://wix.com

**Comment by RafaelCanarei5** [comment]
https://eduardocanarei.wixsite.com/dizar-technologies

I think this can be the start point...

**Comment by Luciana478** [comment]
Cool! But the buttons **don't works!**

**Comment by RafaelCanarei5** [comment]
How we can make this better?

**Comment by Luciana478** [comment]
Let's incorporate HTML!

**Comment by RafaelCanarei5** [comment]
Let _me_ do this!

**Comment by Taiane34** [comment]
I can help ya! I have completed a course in JS!

**Comment by RafaelCanarei5** [comment]
Yeah, and i don't know any line in JavaScript!

**Comment by Taiane34** [comment]
Yeah, it's really complicated, but it would be simple to us!

**Comment by Luciana478** [comment]
### Thank you to use this issue!
If ya wanna to open this issue again, ask for me.
